// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC5kLRCoz-Z1SxlGcGlsJD5rms_XRyg6HA",
      authDomain: "sungura-project.firebaseapp.com",
      projectId: "sungura-project",
      storageBucket: "sungura-project.firebasestorage.app",
      messagingSenderId: "64371233764",
      appId: "1:64371233764:web:1087e590e2da52cd502df1");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs88NtnLB7kfJftD7dKQKeZhQWGB-7BpI',
    appId: '1:64371233764:android:8de502be64e8292a502df1',
    messagingSenderId: '64371233764',
    projectId: 'sungura-project',
    storageBucket: 'sungura-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRWPUfh_krEYHQl9XR7jkv4ebSVuJmXw',
    appId: '1:64371233764:ios:075d045cac25219c502df1',
    messagingSenderId: '64371233764',
    projectId: 'sungura-project',
    storageBucket: 'sungura-project.appspot.com',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRWPUfh_krEYHQl9XR7jkv4ebSVuJmXw',
    appId: '1:64371233764:ios:075d045cac25219c502df1',
    messagingSenderId: '64371233764',
    projectId: 'sungura-project',
    storageBucket: 'sungura-project.appspot.com',
    iosBundleId: 'com.example.frontEnd',
  );
}
